### ISSUE TITLE
Impossible de scanner des cartes après verrouillage/déverrouillage

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-nfc-tag-droid#3]
Scénario :
- Lancer EsupNfcTagDroid
- Scanner une carte : ça marche
- Si une popup de confirmation s'est affichée, cliquer sur Annuler
- Laisser la carte collée derrière le téléphone
- Verrouiller l'écran avec le bouton : le téléphone fait un bruit de type "erreur NFC"
- Enlever la carte
- Déverrouiller le téléphone
- Scanner une ou plusieurs autres cartes : ça ne marche pas (bruit de type "erreur NFC")

Pour résoudre le problème :
- Appuyer sur le bouton de l'écran d'accueil, puis relancer l'application

Contournement pour éviter le problème :
- Enlever la carte avant de verrouiller le téléphone

Ce problème est très gênant pour les surveillants qui doivent scanner de nombreuses cartes à la chaîne. Si pour une raison ou une autre ils verrouillent leur téléphone en laissant une carte derrière, ils vont déclencher le bug. Et ensuite ils n'arriveront plus à scanner d'autres cartes.

**Comment by vinriviere** [comment]
En fait le problème est intermittent.
Au moment où j'ai écrit le scénario ci-dessus, je le reproduisais à tous les coups.
Maintenant (quelques minutes après) je n'arrive plus à le reproduire.
Alors que j'ai eu très souvent ce souci depuis que je teste l'application.

Rencontrez-vous également ce problème ?

**Comment by vinriviere** [comment]
Ce problème arrivé régulièrement sur téléphone OnePlus 8T.
Mais je ne le reproduis pas sur Samsung Galaxy A03.
Donc c'est peut-être un bug spécifique au OnePlus 8T.

**Comment by vbonamy** [comment]
Bonjour Vincent,

Je réponds (enfin !) à cette issue qui devrait t'apporter également des éléments d'information sur les autres issues, notamment #8 voire #7 ... et possiblement même https://github.com/EsupPortail/esup-emargement/issues/7

Dans son mode par badgeage de carte et en lien avec esup-nfc-tag, l'objectif d'esup-emargement est de "vider" les amphis le plus rapidement possible. L'idée est donc de badger/émarger effectivement à la chaîne.

Lors du retour réalisé il y a presque un an maintenant par l'université de rouen à EsupDays 33, les collègues expliquaient émarger en moyenne 200 étudiants en 10 minutes avec 2 terminaux (contre 45 minutes lorsque l'émargement se faisait en papier).
CF https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=1083670533#ESUPDaysn%C2%B033/ApereoParis2022-14:00%E2%80%93esup-emargement,d%C3%A9mat%C3%A9rialisationdel'%C3%A9margementenlienavecleSI

Tout cela pour dire qu'il faut donc ici imaginer un badgeage rapide et en continue.

Aussi, on configure l'application emargement côté esup-nfc-tag pour valider par défaut sans confirmation du gestionnaire.

Dans ce type de scénario, il n'est donc pas vraiment question de verrouiller le téléphone avec une carte dessous par exemple.

Bref, je ne dis pas qu'il n'y a pas un problème ou bug avec l'usage du NFC et le verrouilllage / déverrouillage du téléphone ; d'autant que j'avoue qu'on n'a pas regarder/étudier la question de proposer à esup-nfc-atg-droid de prendre la main sur le badgeage NFC quand celui-ci n'est pas allumé (je crois que c'est possible). 
Par contre je ne pense pas que  ça corresponde (du moins chez nous) à un réel cas d'usage de nos collègues utilisant effectivement cette application en production.

Qu'en penses-tu ?

Merci,
Vincent.

**Comment by vinriviere** [comment]
Bonjour Vincent,
Merci pour cette réponse.
En fait, j'ai ouvert cette Issue car je n'arrête pas de tomber sur ce problème durant mes tests. Et c'est gênant car je me demande toujours si j'ai mal badgé, ou si j'ai mal configuré quelque chose. Mais effectivement, dans un scénario standard, personne ne devrait mettre en veille le téléphone alors qu'il reste sur une carte. Je ne sais pas si ce problème se produit également dans d'autres scénarios.

Quoi qu'il en soit, comme je l'ai dit plus haut, je me heurte très souvent à ce problème sur OnePlus 8T, mais je ne l'ai jamais reproduit sur Samsung Galaxy A03. Donc il semble que ce soit en fait un bug spécifique au OnePlus 8T (et la mise à niveau Android 12 vers 13 n'a rien changé).

Dans ces conditions, je propose tout simplement qu'on ferme cette Issue. On pourra toujours s'y référer si quelqu'un d'autre rencontre ce problème sur un autre téléphone.

**Comment by vbonamy** [comment]
Bonjour Vincent,

Effectivement le choix des téléphones n'est pas anodin. 

Ici avant d'acheter une flotte de téléphones mobiles (Android) pour les agents, on vérifie qu'ils sont NFC et qu'ils sont assez réactifs pour le badgeage avec esup-nfc-tag (== avant d'acheter des 10 aines de téléphones d'un même modèle, on en achète et on en teste 1, notamment via esup-nfc-tag).

On constate que suivant les modèles, les téléphones sont +/- rapides et ergonomiques pour le badgeage.

Cela nous permet ainsi de donner une 2 ème vie aux téléphones rendues par les agents qui demandent à acquérir un nouveau téléphone : on réutilise / reconvertit les anciens téléphones comme périphériques de badgeage.

Un téléphone qu'on a plutôt apprécié (et qu'on a encore en service ici comme périphérique de badgeage) est le "Samsung Galaxy Core Prime" par exemple (date de 2014 ; plus en vente évidemment, et 'bloqué' sur une version Android assez ancienne maintenant ... mais esup-nfc-tag-droid, qu'on a voulu être "codé dans le marbre" quasiment, si j'ose dire, ne demande pas de version Android récente).

Je clos cette issue.
Vincent.
